version: '3.7'

services:
    btcd:
        image: ruimarinho/bitcoin-core:0.21
        container_name: btcd
        hostname: btcd
        restart: unless-stopped
        command:
            -printtoconsole
            -rpcport=8332
            -server=1
            -txindex=1
            -peerbloomfilters=1
            -dbcache=1000
            -maxconnections=800
            -timeout=30000
            -listen=1
            -rpcuser=${RPC_USER}
            -rpcallowip=172.28.1.3
            -rpcpassword=${RPC_PASSWORD}
        ports:
            - 8333:8333
            - 18443:18443
        volumes:
            - ${BTC_DATA_DIR}:/home/bitcoin/.bitcoin/

    tor:
        image: goldy/tor-hidden-service:$TOR_VERSION
        container_name: tor
        restart: unless-stopped
        links:
            - btcd
        environment:
            # Set mapping ports
            BTCD_TOR_SERVICE_HOSTS: 8333:btcd:8333
            BTCD_TOR_SERVICE_VERSION: '2'

            BTCD3_TOR_SERVICE_HOSTS: 8333:btcd:8333
            BTCD3_TOR_SERVICE_VERSION: '3'
        # Keep keys in volumes
        volumes:
        - tor-keys:/var/lib/tor/hidden_service/

        # Set secret for key, use the same name as the service
        secrets:
          - btcd
          - btcd3

volumes:
    tor-keys:
        driver: local

secrets:
    btcd:
        file: ${TOR_PRIVATE_KEY_FILE}
    btcd3:
        file: ${TOR_PRIVATE_KEY_V3_FILE}

